### ISSUE TITLE
Experiment images

### ISSUE THREAD

**Issue by MarcScott** [uktechreviews/science-tasks#1]
Would it be possible to get photographs of the experimental apparatus setup.
If this is an issue, then had drawn diagrams would be great, and we can get our illustrator to use them as a basis for styled diagrams

**Comment by uktechreviews** [comment]
No problem, I will add hand drawn diagrams of the apparatus setup.

**Comment by uktechreviews** [comment]
I have added a photo and diagram of the apparatus.  I also added quantities of solutions into the teachers notes
![diagram](https://cloud.githubusercontent.com/assets/9432729/10760142/f961e986-7cb2-11e5-8a1d-4a1b091b5488.png)
![rates_apparatus](https://cloud.githubusercontent.com/assets/9432729/10760147/feb664e8-7cb2-11e5-8591-1bad5608ec6b.png)
