### ISSUE TITLE
Lesson 7 - image

### ISSUE THREAD

**Issue by MarcScott** [uktechreviews/science-tasks#2]
Could you please include an image of the apparatus set-up in Lesson 7, to include positioning of the picamera.

**Comment by uktechreviews** [comment]
/Users/local/Downloads/IMG_1891-1.JPG
/Users/local/Downloads/IMG_1889.JPG
/Users/local/Downloads/IMG_1891.JPG
/Users/local/Downloads/IMG_1892.JPG

**Comment by uktechreviews** [comment]
sample images added
